[package]
name = "simple_salary"
version = "1.0.0"
authors = []

[addresses]
simple_salary_addr='0x5fb93bacc36172ad190451674928432e1b829ed7bb8230777f1aeb7eefd03357'

[dev-addresses]

[dependencies.AptosFramework]
git = "https://github.com/aptos-labs/aptos-core.git"
rev = "mainnet"
subdir = "aptos-move/framework/aptos-framework"

[dev-dependencies]
